[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_MENU_URL = "https://rusticpub.netlify.app"
  SECRETS_SCAN_OMIT_KEYS = "ADMIN_USER,NEXT_PUBLIC_CONTACT_WHATSAPP,NEXT_PUBLIC_INSTAGRAM_URL,NEXT_PUBLIC_MENU_URL,NEXT_PUBLIC_RECAPTCHA_SITE_KEY,NEXT_PUBLIC_SITE_URL"
